In [1]:
import tensorflow as tf
import numpy as np
import csv

import pandas as pd

In [7]:
def create_correlation_matrix(prob_of_sentences):
    num_sentences = 4
    correlation_matrix = np.empty(shape=(num_sentences, num_sentences), dtype=float, order='C')
    index=0
    for i in range(num_sentences):
        for j in range(num_sentences):
            if i==j:
                correlation_matrix[i][j]=0
            else:
                correlation_matrix[i][j] = prob_of_sentences[index]
            index+=1
    return correlation_matrix

In [11]:
dataset = pd.read_csv("test_results.tsv", delimiter = '\t')
dataset

True_prob  False_prob
0    0.510609    0.489391
1    0.511671    0.488329
2    0.505276    0.494724
3    0.507776    0.492225
4    0.497947    0.502053
..        ...         ...
75   0.512735    0.487265
76   0.508551    0.491449
77   0.508274    0.491726
78   0.511109    0.488890
79   0.516941    0.483059

[80 rows x 2 columns]

In [12]:
probs = []
for prob in dataset.True_prob:
    probs.append(prob)

In [13]:
len(probs)

80

In [14]:
for i in range(len(probs)//16):  
    prob_of_sentences=probs[i*16:i*16+16]
    matrix = create_correlation_matrix(prob_of_sentences)
    print(matrix)

[[0.         0.51167077 0.5052764  0.5077755 ]
 [0.51060915 0.         0.5052764  0.5077755 ]
 [0.51060915 0.51167077 0.         0.5077755 ]
 [0.51060915 0.51167077 0.5052764  0.        ]]
[[0.         0.51603055 0.51265126 0.5154321 ]
 [0.51989365 0.         0.51265126 0.5154321 ]
 [0.51989365 0.51603055 0.         0.5154321 ]
 [0.51989365 0.51603055 0.51265126 0.        ]]
[[0.         0.52119523 0.53059506 0.5106899 ]
 [0.5174144  0.         0.53059506 0.5106899 ]
 [0.5174144  0.52119523 0.         0.5106899 ]
 [0.5174144  0.52119523 0.53059506 0.        ]]
[[0.         0.50447714 0.5092094  0.51017064]
 [0.5097555  0.         0.5092094  0.51017064]
 [0.5097555  0.50447714 0.         0.51017064]
 [0.5097555  0.50447714 0.5092094  0.        ]]
[[0.         0.51223916 0.5127419  0.5128507 ]
 [0.5153158  0.         0.5127419  0.5128507 ]
 [0.5153158  0.51223916 0.         0.5128507 ]
 [0.5153158  0.51223916 0.5127419  0.        ]]


In [17]:
with open('test_results_ordering_prob.tsv', 'wt', -1, "utf-8") as out_file:
    tsv_writer = csv.writer(out_file, delimiter='\t')
    tsv_writer.writerow(['1-2', '2-3', '3-4'])
    for i in range(len(probs)//16):  
        prob_of_sentences=probs[i*16:i*16+16]
        matrix = create_correlation_matrix(prob_of_sentences)
        print(matrix)
    
        prob_1_2 = matrix[0][1]
        prob_2_3 = matrix[1][2]
        prob_3_4 = matrix[2][3]
        
        tsv_writer.writerow([prob_1_2, prob_2_3, prob_3_4])

[[0.         0.51167077 0.5052764  0.5077755 ]
 [0.51060915 0.         0.5052764  0.5077755 ]
 [0.51060915 0.51167077 0.         0.5077755 ]
 [0.51060915 0.51167077 0.5052764  0.        ]]
[[0.         0.51603055 0.51265126 0.5154321 ]
 [0.51989365 0.         0.51265126 0.5154321 ]
 [0.51989365 0.51603055 0.         0.5154321 ]
 [0.51989365 0.51603055 0.51265126 0.        ]]
[[0.         0.52119523 0.53059506 0.5106899 ]
 [0.5174144  0.         0.53059506 0.5106899 ]
 [0.5174144  0.52119523 0.         0.5106899 ]
 [0.5174144  0.52119523 0.53059506 0.        ]]
[[0.         0.50447714 0.5092094  0.51017064]
 [0.5097555  0.         0.5092094  0.51017064]
 [0.5097555  0.50447714 0.         0.51017064]
 [0.5097555  0.50447714 0.5092094  0.        ]]
[[0.         0.51223916 0.5127419  0.5128507 ]
 [0.5153158  0.         0.5127419  0.5128507 ]
 [0.5153158  0.51223916 0.         0.5128507 ]
 [0.5153158  0.51223916 0.5127419  0.        ]]
