In [5]:
import tensorflow as tf
import numpy as np
import csv

import pandas as pd

In [6]:
def create_correlation_matrix(prob_of_sentences):
    num_sentences = 4
    correlation_matrix = np.empty(shape=(num_sentences, num_sentences), dtype=float, order='C')
    index=0
    for i in range(num_sentences):
        for j in range(num_sentences):
            if i==j:
                correlation_matrix[i][j]=0
            else:
                correlation_matrix[i][j] = prob_of_sentences[index]
            index+=1
    return correlation_matrix

In [7]:
dataset = pd.read_csv("test_results.tsv", delimiter = '\t')
dataset

True_prob  False_prob
0     0.457648    0.542352
1     0.435944    0.564056
2     0.435736    0.564264
3     0.418591    0.581409
4     0.433058    0.566942
..         ...         ...
795   0.456676    0.543324
796   0.442014    0.557986
797   0.437441    0.562559
798   0.455828    0.544172
799   0.460673    0.539327

[800 rows x 2 columns]

In [9]:
probs = []
for prob in dataset.True_prob:
    probs.append(prob)

In [10]:
len(probs)

800

In [11]:
for i in range(len(probs)//16):  
    prob_of_sentences=probs[i*16:i*16+16]
    matrix = create_correlation_matrix(prob_of_sentences)
    print(matrix)

[[0.         0.43594408 0.43573564 0.4185907 ]
 [0.4330577  0.         0.44841594 0.42843038]
 [0.43112335 0.44670457 0.         0.44701838]
 [0.429927   0.43734583 0.44498965 0.        ]]
[[0.         0.45935884 0.45388576 0.4539368 ]
 [0.44958255 0.         0.45246264 0.44697848]
 [0.44446486 0.45031884 0.         0.44739234]
 [0.44414878 0.4425198  0.44561994 0.        ]]
[[0.         0.3875512  0.49660558 0.4953167 ]
 [0.4282022  0.         0.4431437  0.44848883]
 [0.50976074 0.42575687 0.         0.41910815]
 [0.45117635 0.42846963 0.40991887 0.        ]]
[[0.         0.45203152 0.43870267 0.39480782]
 [0.4495311  0.         0.4558001  0.45496404]
 [0.43690893 0.45618802 0.         0.45766973]
 [0.42058212 0.4539784  0.45633867 0.        ]]
[[0.         0.45346546 0.45544937 0.45705864]
 [0.45216095 0.         0.45610178 0.44695735]
 [0.4520747  0.4531044  0.         0.44967246]
 [0.45344558 0.4475003  0.44827577 0.        ]]
[[0.         0.44490403 0.43074068 0.38206783]
 [0.4402

In [12]:
with open('test_results_ordering_prob_50.tsv', 'wt', -1, "utf-8") as out_file:
    tsv_writer = csv.writer(out_file, delimiter='\t')
    tsv_writer.writerow(['1-2', '2-3', '3-4'])
    for i in range(len(probs)//16):  
        prob_of_sentences=probs[i*16:i*16+16]
        matrix = create_correlation_matrix(prob_of_sentences)
        print(matrix)
    
        prob_1_2 = matrix[0][1]
        prob_2_3 = matrix[1][2]
        prob_3_4 = matrix[2][3]
        
        tsv_writer.writerow([prob_1_2, prob_2_3, prob_3_4])

[[0.         0.43594408 0.43573564 0.4185907 ]
 [0.4330577  0.         0.44841594 0.42843038]
 [0.43112335 0.44670457 0.         0.44701838]
 [0.429927   0.43734583 0.44498965 0.        ]]
[[0.         0.45935884 0.45388576 0.4539368 ]
 [0.44958255 0.         0.45246264 0.44697848]
 [0.44446486 0.45031884 0.         0.44739234]
 [0.44414878 0.4425198  0.44561994 0.        ]]
[[0.         0.3875512  0.49660558 0.4953167 ]
 [0.4282022  0.         0.4431437  0.44848883]
 [0.50976074 0.42575687 0.         0.41910815]
 [0.45117635 0.42846963 0.40991887 0.        ]]
[[0.         0.45203152 0.43870267 0.39480782]
 [0.4495311  0.         0.4558001  0.45496404]
 [0.43690893 0.45618802 0.         0.45766973]
 [0.42058212 0.4539784  0.45633867 0.        ]]
[[0.         0.45346546 0.45544937 0.45705864]
 [0.45216095 0.         0.45610178 0.44695735]
 [0.4520747  0.4531044  0.         0.44967246]
 [0.45344558 0.4475003  0.44827577 0.        ]]
[[0.         0.44490403 0.43074068 0.38206783]
 [0.4402